name: Tak Server CI/CD Beta

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B compile
        mvn -B package
    - name: Prep Artifact
      run : |
        tar -czf artifact-beta.tar.gz ./target/*.jar
    - name: Deploy
        env: 
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME }}
            USER_NAME : ${{ secrets.USER_NAME }}
            SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 0400 private_key.pem
          scp -P ${SSH_PORT} -o StrictHostKeyChecking=no -i private_key.pem artifact-beta.tar.gz ${USER_NAME}@${HOSTNAME}:~
          ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            source ~/.nvm/nvm.sh
            rm -rf playtak-api-tmp
            mkdir playtak-server-tmp
            tar -xzf artifact-beta.tar.gz -C ./playtak-server-tmp
          '